version: '3'

services:
 sequences:
  image: sequences
  build:
   context: .
   dockerfile: Dockerfile
  ports:
   - "8888:8888"
  command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''"
  volumes:
   - .:/home/jovyan

